name: adyen_checkout_example
description: Demonstrates how to use the adyen_checkout plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  adyen_checkout:
    path: ../
  http: ^1.2.0
  collection: ^1.18.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.10

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/card_brands/
