name: Assign Reviewers

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Assign Android reviewer
        if: contains(steps.changed-files.outputs.all_changed_files, '.kt') ||
          contains(steps.changed-files.outputs.all_changed_files, '.java') ||
          contains(steps.changed-files.outputs.all_changed_files, '.gradle') ||
          contains(steps.changed-files.outputs.all_changed_files, '/android/')
          contains(steps.changed-files.outputs.all_changed_files, '.xml')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              team_reviewers: ['@Adyen/checkout-android']
            });

      - name: Assign iOS reviewer
        if: contains(steps.changed-files.outputs.all_changed_files, '.swift') ||
          contains(steps.changed-files.outputs.all_changed_files, '.m') ||
          contains(steps.changed-files.outputs.all_changed_files, '.storyboard') ||
          contains(steps.changed-files.outputs.all_changed_files, '.xib') ||
          contains(steps.changed-files.outputs.all_changed_files, '.pbxproj') ||
          contains(steps.changed-files.outputs.all_changed_files, '/ios/')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              team_reviewers: ['@Adyen/checkout-ios ']
            });