name: Clean up cache

on:
  pull_request_target:
    branches: [ "main" ]
    types: [ closed ]
  push:
    branches: [ "main" ]

permissions:
  actions: write

jobs:
  clean_up:
    name: Clean up
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Clear cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          gh cache delete android-reports || true
          gh cache delete ios-reports || true
