name: Swift unit tests

on:
  workflow_call:
    inputs:
      flutter-version:
        description: 'Flutter version'
        required: true
        default: '3.29.x'
        type: string

permissions:
  contents: read

jobs:
  ios_tests:
    runs-on: macos-26
    timeout-minutes: 45
    defaults:
      run:
        working-directory: example/ios

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: 'stable'
          cache: true

      - run: flutter doctor -v
      - run: flutter clean
      - run: flutter pub get

      - name: Pod install
        run: pod install

      - name: Lint check
        working-directory: ios
        run: |
          brew install swiftlint
          fastlane run swiftlint config_file:".swiftlint.yml" output_file:"swiftLintReport.json" reporter:"json"

      - name: Cache iOS reports
        uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: save-iOS-reports
        with:
          path: ios/
          key: ios-reports

      - name: Running iOS unit tests
        working-directory: example/ios
        env:
          DESTINATION: "platform=iOS Simulator,name=iPhone 17,OS=26.1"
        run: |
            set -o pipefail
            xcodebuild test -workspace Runner.xcworkspace -scheme Runner -destination "$DESTINATION" -enableCodeCoverage YES | xcpretty --utf --color